stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
      - src/data/data_collection.py
    outs:
      - data/row
  
  data_preprocess:
    cmd: python src/data/data_prep.py
    deps:
      - data/row
      - src/data/data_prep.py
    outs:
      - data/process
